# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IGESS <- function(Xs, y, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, verbose = FALSE) {
    .Call('_IGESS_IGESS', PACKAGE = 'IGESS', Xs, y, SS, opts, logfile, lbPval, verbose)
}

IGESSCV <- function(Xs, y, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, measure = "mse") {
    .Call('_IGESS_IGESSCV', PACKAGE = 'IGESS', Xs, y, SS, opts, logfile, lbPval, measure)
}

IGESS_Plink <- function(genoplinkfile, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12) {
    .Call('_IGESS_IGESS_Plink', PACKAGE = 'IGESS', genoplinkfile, SS, opts, logfile, lbPval)
}

IGESSCV_Plink <- function(genoplinkfile, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, measure = "mse") {
    .Call('_IGESS_IGESSCV_Plink', PACKAGE = 'IGESS', genoplinkfile, SS, opts, logfile, lbPval, measure)
}

IGESS_Predict <- function(fit_, X) {
    .Call('_IGESS_IGESS_Predict', PACKAGE = 'IGESS', fit_, X)
}

